[package]
name = "rs-balancer"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
clap = "4.5.53"
log = "0.4.29"
pingora = "0.6.0"
pingora-http = "0.6.0"
pingora-load-balancing = "0.6.0"
pingora-proxy = "0.6.0"
